<?php

/**
 * Implements hook_form_FORM_ID_alter().
 * Sets the default post date to the last post's date + 1 day, but only if the
 * last post is in the future.
 */
function pba_ephemeris_form_node_post_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $query = \Drupal::entityQuery('node');
  $query->condition('type', 'post');
  $query->sort('field_date', 'DESC');
  $query->range(0, 1);
  $nids = $query->execute();
  if ($nids) {
    $last_post = \Drupal\node\Entity\Node::load(current($nids));
    $date = new \Drupal\Core\Datetime\DrupalDateTime($last_post->get('field_date')->value);
    if ($date > new \Drupal\Core\Datetime\DrupalDateTime()) {
      $form['field_date']['widget'][0]['value']['#default_value'] = $date->add(new DateInterval('P1D'));
    }
  }
}

/**
 * @param \Drupal\node\Entity\Node $node
 * @param string $direction
 *
 * @return \Drupal\node\Entity\Node|null
 */
function _pba_ephemeris_adjacent_post(\Drupal\node\Entity\Node $node, $direction = 'prev') {
  $query = \Drupal::entityQuery('node');
  $query->condition('type', 'post');
  $query->condition('status', \Drupal\node\NodeInterface::PUBLISHED);
  $query->condition('field_date', $node->get('field_date')->value, $direction === 'next' ? '>' : '<');
  $query->sort('field_date', $direction === 'next' ? 'ASC' : 'DESC');
  $query->range(0, 1);
  $nids = $query->execute();
  if (!$nids)
    return NULL;
  return \Drupal\node\Entity\Node::load(current($nids));
}

/**
 * Implements hook_entity_view_alter().
 */
function pba_ephemeris_entity_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  if ($entity->getEntityTypeId() !== 'node' || $entity->bundle() !== 'post') {
    return;
  }
  switch ($display->getOriginalMode()) {
    case 'full':
      $view_builder = \Drupal::entityTypeManager()->getViewBuilder('node');

      $prev = _pba_ephemeris_adjacent_post($entity, 'prev');
      if ($prev) {
        $build['prev'] = [
          '#type' => 'container',
          '#weight' => 100,
          '#attributes' => ['class' => ['prev']],
          'node' => $view_builder->view($prev, 'teaser'),
        ];
      }

      $next = _pba_ephemeris_adjacent_post($entity, 'next');
      if ($next) {
        $build['next'] = [
          '#type' => 'container',
          '#weight' => 101,
          '#attributes' => ['class' => ['next']],
          'node' => $view_builder->view($next, 'teaser'),
        ];
      }
      break;
    case 'teaser':
      $build['title']['#access'] = FALSE;
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function pba_ephemeris_node_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->bundle() !== 'post')
    return;

  foreach (['prev', 'next'] as $direction) {
    $adjacent = _pba_ephemeris_adjacent_post($entity, $direction);
    if (!$adjacent)
      continue;

    \Drupal\Core\Cache\Cache::invalidateTags($adjacent->getCacheTagsToInvalidate());
  }
}

/**
 * Implements hook_theme().
 */
function pba_ephemeris_theme($existing, $type, $theme, $path) {
  return [
    'sidebar_calendar_month' => [
      'variables' => [
        'date' => NULL,
      ],
    ],
    'sidebar_calendar_year' => [
      'variables' => [
        'date' => NULL,
        'months' => NULL,
      ],
    ],
    'sidebar_calendar' => [
      'variables' => [
        'years' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function pba_ephemeris_preprocess_sidebar_calendar_month(&$variables) {
  /** @var \Drupal\node\Entity\Node|NULL $current_post */
  $current_post = \Drupal::routeMatch()->getParameter('node');

  /** @var \Drupal\Core\Datetime\DrupalDateTime $from */
  $from = $variables['date'];
  $to = clone $from;
  $to->add(new DateInterval('P1M'));
  $posts_by_date = [];

  $query = \Drupal::entityQuery('node');
  $query->condition('type', 'post');
  $query->condition('status', \Drupal\node\NodeInterface::PUBLISHED);
  $query->condition('field_date', $from, '>=');
  $query->condition('field_date', $to, '<');
  $nids = $query->execute();

  if ($nids)
    /** @var \Drupal\node\Entity\Node $post */
    foreach (\Drupal\node\Entity\Node::loadMultiple($nids) as $post) {
      $date = new \Drupal\Core\Datetime\DrupalDateTime($post->get('field_date')->value);
      $posts_by_date[intval($date->format('j'))] = [
        'url' => $post->toUrl(),
        'date' => $date,
        'class' => $current_post && $post->id() === $current_post->id() ? 'active' : NULL,
      ];
    }

  $variables['posts_by_date'] = $posts_by_date;
}
